### ISSUE TITLE
Flattening does not include root xmlns on schema

### ISSUE THREAD

**Issue by veewee** [php-soap/wsdl#15]
### Bug Report

See https://github.com/phpro/soap-client/issues/495

view-source:https://immobinetagenzie.immobinet.it/webservices/webservicemodagenzia/service.wsdl
view-source:https://immobinetagenzie.immobinet.it/webservices-deps/webservicecore/schema.xsd

Results in flattened:

```xml
    <xsd:schema xmlns:imm="http://www.immobinet.it/schema/WebserviceCoreBundle" targetNamespace="http://www.immobinet.it/schema/WebserviceCoreBundle" elementFormDefault="qualified">
```

But should be:

```xml
    <xsd:schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:imm="http://www.immobinet.it/schema/WebserviceCoreBundle" targetNamespace="http://www.immobinet.it/schema/WebserviceCoreBundle" elementFormDefault="qualified">
```

Resulting in XSD's "string" to be unknown cause it is not prefixed:

```
  Can't find type named {http://www.immobinet.it/schema/WebserviceCoreBundle}#string, at line 309 in immobinet.it.wsdl
```

**Comment by veewee** [comment]
This seems to be an `ext-dom` issue.
See more details in this gist: https://gist.github.com/veewee/32c3aa94adcf878700a9d5baa4b2a2de

To overcome this, an additional XMLNS copying check must be wrapped when appending the external node:
https://github.com/php-soap/wsdl/blob/22a8fce96a8d151004fa4e639c6968ec0aa33878/src/Xml/Configurator/FlattenXsdImports.php#L190-L192

However, since this looks like a PHP bug, it might make more sense to try get it solved there.

**Comment by nielsdos** [comment]
> However, since this looks like a PHP bug, it might make more sense to try get it solved there.

I received your e-mail this week and I have replied to it, but I'm not sure if you got my reply.

**Comment by veewee** [comment]
Oh snap ... it was delivered in my spam folder :)
